# Generated by Django 5.0.4 on 2024-04-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('num_pages', models.IntegerField()),
                ('editorial', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=500)),
                ('stand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookbuddyapp.stand')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookbuddyapp.user')),
            ],
        ),
    ]
